apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "navansatt"
  namespace: "pensjondeployer"
  labels:
    team: "pensjondeployer"
spec:
  image: "{{{ image }}}"
  port: 7000
  replicas:
    min: 2
    max: 8
  liveness:
    path: "/internal/isalive"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "/internal/metrics"
  readiness:
    path: "/internal/isready"
    initialDelay: 3
    timeout: 1
  resources:
    limits:
      memory: "4096Mi"
    requests:
      memory: "2048Mi"
  ingresses:
    - "https://navansatt.intern.nav.no"
    - "https://navansatt.prod-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-oracle-revisjon-backend
          namespace: pensjon-revisjon
          cluster: prod-fss
        - application: pensjon-oracle-revisjon-backend-popp
          namespace: pensjon-revisjon
          cluster: prod-fss
        - application: pensjon-oracle-revisjon-backend-pen-q2
          namespace: pensjon-revisjon
          cluster: dev-fss
        - application: pensjon-oracle-revisjon-backend
          namespace: pensjon-revisjon
          cluster: dev-fss
        - application: pensjon-pen
          namespace: pensjondeployer
        - application: pensjon-psak
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-psak
          namespace: pensjondeployer
          cluster: prod-gcp
        - application: etterlatte-brev-api
          namespace: etterlatte
          cluster: prod-gcp
        - application: etterlatte-behandling
          namespace: etterlatte
          cluster: prod-gcp
        - application: eessi-pensjon-journalforing
          namespace: eessipensjon
          cluster: prod-gcp
        - application: skribenten-backend
          namespace: pensjonsbrev
          cluster: prod-gcp
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
  webproxy: true
  env:
    - name: "LDAP_URL"
      value: "ldaps://ldapgw.adeo.no"
    - name: "LDAP_BASE"
      value: "dc=adeo,dc=no"
    - name: "AXSYS_URL"
      value: "https://axsys.intern.nav.no"
    - name: "NORG2_URL"
      value: "https://norg2.intern.nav.no/norg2"
    - name: "STS_WELL_KNOWN_URL"
      value: "https://security-token-service.nais.adeo.no/.well-known/openid-configuration"
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=p"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/prod/srvssolinux"
        mountPath: "/secrets/ldap"
