apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "navansatt"
  namespace: "teampensjon"
  labels:
    team: "teampensjon"
spec:
  image: "{{{ image }}}"
  port: 7000
  replicas:
    min: 2
    max: 4
  liveness:
    path: "/internal/isalive"
    initialDelay: 3
    timeout: 1
  readiness:
    path: "/internal/isready"
    initialDelay: 3
    timeout: 1
  resources:
    limits:
      memory: "1024Mi"
    requests:
      memory: "512Mi"
  prometheus:
    enabled: true
    path: "/internal/metrics"
  ingresses:
    - "https://navansatt.dev.adeo.no"
    - "https://navansatt.dev.intern.nav.no"
    - "https://navansatt.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q0
          namespace: teampensjon
        - application: pensjon-pen-q1
          namespace: teampensjon
        - application: pensjon-pen-q2
          namespace: teampensjon
        - application: pensjon-pen-q4
          namespace: teampensjon
        - application: pensjon-pen-q5
          namespace: teampensjon
        - application: pensjon-psak-q0
          namespace: teampensjon
        - application: pensjon-psak-q1
          namespace: teampensjon
        - application: pensjon-psak-q2
          namespace: teampensjon
        - application: pensjon-psak-q4
          namespace: teampensjon
        - application: pensjon-psak-q5
          namespace: teampensjon
        - application: etterlatte-brev-api
          namespace: etterlatte
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
  webproxy: true
  env:
    - name: "LDAP_URL"
      value: "ldaps://ldapgw.preprod.local"
    - name: "LDAP_BASE"
      value: "dc=preprod,dc=local"
    - name: "AXSYS_URL"
      value: "https://axsys.dev.intern.nav.no"
    - name: "NORG2_URL"
      value: "https://norg2.dev-fss.nais.io/norg2"
    - name: "OPENAM_WELL_KNOWN_URL"
      value: "https://isso-q.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: "STS_WELL_KNOWN_URL"
      value: "https://security-token-service.nais.preprod.local/.well-known/openid-configuration"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/dev/srvssolinux"
        mountPath: "/secrets/ldap"
