apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "navansatt"
  namespace: "pensjondeployer"
  labels:
    team: "pensjondeployer"
spec:
  image: "{{{ image }}}"
  port: 7000
  replicas:
    min: 2
    max: 4
  liveness:
    path: "/internal/isalive"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "/internal/metrics"
  readiness:
    path: "/internal/isready"
    initialDelay: 3
    timeout: 1
  resources:
    limits:
      memory: "1024Mi"
    requests:
      memory: "512Mi"
  ingresses:
    - "https://navansatt.intern.nav.no"
  azure:
    application:
      enabled: true
      tenant: nav.no
  webproxy: true
  env:
    - name: "LDAP_URL"
      value: "ldaps://ldapgw.adeo.no"
    - name: "LDAP_BASE"
      value: "dc=adeo,dc=no"
    - name: "AXSYS_URL"
      value: "https://axsys.intern.nav.no/"
    - name: "NORG2_URL"
      value: "https://norg2.nais.adeo.no/norg2"
    - name: "OPENAM_WELL_KNOWN_URL"
      value: "https://isso.adeo.no/isso/oauth2/.well-known/openid-configuration"
    - name: "STS_WELL_KNOWN_URL"
      value: "https://security-token-service.nais.adeo.no/.well-known/openid-configuration"
  vault:
    enabled: true
    paths:
      - kvPath: "serviceuser/data/prod/srvssolinux"
        mountPath: "/secrets/ldap"
