apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "navansatt"
  namespace: "teampensjon"
  labels:
    team: "teampensjon"
spec:
  image: "{{{ image }}}"
  port: 7000
  replicas:
    min: 2
    max: 4
  liveness:
    path: "/internal/isalive"
    initialDelay: 3
    timeout: 1
  readiness:
    path: "/internal/isready"
    initialDelay: 3
    timeout: 1
  resources:
    limits:
      memory: "1024Mi"
    requests:
      memory: "512Mi"
  prometheus:
    enabled: true
    path: "/internal/metrics"
  ingresses:
    - "https://navansatt.intern.dev.nav.no"
#    - "https://navansatt.dev.adeo.no"
#    - "https://navansatt.dev.intern.nav.no"
#    - "https://navansatt.dev-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-pen-q0
          namespace: pensjon-q0
          cluster: dev-fss
        - application: pensjon-pen-q1
          namespace: pensjon-q1
          cluster: dev-fss
        - application: pensjon-pen-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-pen-q5
          namespace: pensjon-q5
          cluster: dev-fss
        - application: pensjon-psak-q0
          namespace: pensjon-q0
          cluster: dev-fss
        - application: pensjon-psak-q1
          namespace: pensjon-q1
          cluster: dev-fss
        - application: pensjon-psak-q2
          namespace: pensjon-q2
          cluster: dev-fss
        - application: pensjon-psak-q2
          namespace: pensjon-q2
          cluster: dev-gcp
        - application: pensjon-psak-q5
          namespace: pensjon-q5
          cluster: dev-fss
        - application: pensjon-psak-q0
          namespace: pensjon-q0
          cluster: dev-gcp
        - application: pensjon-psak-q1
          namespace: pensjon-q1
          cluster: dev-gcp
        - application: pensjon-psak-q2
          namespace: pensjon-q2
          cluster: dev-gcp
        - application: pensjon-psak-q5
          namespace: pensjon-q5
          cluster: dev-gcp
#        - application: etterlatte-brev-api
#          namespace: etterlatte
#          cluster: dev-gcp
        - application: etterlatte-behandling
          namespace: etterlatte
          cluster: dev-gcp
        - application: eessi-pensjon-journalforing-q2
          namespace: eessipensjon
          cluster: dev-gcp
        - application: eessi-pensjon-journalforing-q1
          namespace: eessipensjon
          cluster: dev-gcp
        - application: ida
          namespace: traktor
          cluster: prod-fss
        - application: skribenten-backend
          namespace: pensjonsbrev
          cluster: dev-gcp
        - application: skribenten-backend-lokal
          namespace: pensjonsbrev
          cluster: dev-gcp
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
    outbond:
      rules:
        - application: entraproxy
          namespace: sikkerhetstjenesten
          cluster: dev-gcp
        - application: norg2
          namespace: org
          cluster: dev-gcp
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
  webproxy: true
  env:
    - name: "NORG2_URL"
      value: "https://norg2.intern.dev.nav.no/norg2"
    - name: "ENTRAPROXY_URL"
      value: "https://entraproxy.intern.dev.nav.no"
    - name: "ENTRAPROXY_SCOPE"
      value: "api://dev-gcp.sikkerhetstjenesten.entra-proxy/.default"
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=q2"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
