apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: navansatt
  namespace: pensjondeployer
  labels:
    team: pensjondeployer
spec:
  image: "{{{ image }}}"
  port: 7000
  replicas:
    min: 2
    max: 8
  liveness:
    path: "/internal/isalive"
    initialDelay: 3
    timeout: 1
  readiness:
    path: "/internal/isready"
    initialDelay: 3
    timeout: 1
  resources:
    limits:
      memory: "4096Mi"
    requests:
      memory: "2048Mi"
  prometheus:
    enabled: true
    path: "/internal/metrics"
  ingresses:
#    - https://navansatt.intern.nav.no
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  azure:
    application:
      enabled: true
      allowAllUsers: true
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-oracle-revisjon-backend
          namespace: pensjon-revisjon
          cluster: prod-fss
        - application: pensjon-oracle-revisjon-backend-popp
          namespace: pensjon-revisjon
          cluster: prod-fss
        - application: pensjon-oracle-revisjon-backend-pen-q2
          namespace: pensjon-revisjon
          cluster: dev-fss
        - application: pensjon-oracle-revisjon-backend
          namespace: pensjon-revisjon
          cluster: dev-fss
        - application: pensjon-pen
          namespace: pensjondeployer
        - application: pensjon-psak
          namespace: pensjondeployer
          cluster: prod-fss
        - application: pensjon-psak
          namespace: pensjondeployer
          cluster: prod-gcp
        - application: etterlatte-behandling
          namespace: etterlatte
          cluster: prod-gcp
        - application: eessi-pensjon-journalforing
          namespace: eessipensjon
          cluster: prod-gcp
        - application: skribenten-backend
          namespace: pensjonsbrev
          cluster: prod-gcp
    outbound:
      rules:
        - application: norg2
          namespace: org
  env:
    - name: NORG2_URL
      value: http://norg2.org/norg2