apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ app.name }}
  namespace: {{ app.namespace }}
  labels:
    team: {{ app.team }}
spec:
  image: "{{{ image }}}"
  port: 7000
  replicas:
    min: 2
    max: 8
  liveness:
    path: "/internal/isalive"
    initialDelay: 3
    timeout: 1
  prometheus:
    enabled: true
    path: "/internal/metrics"
  readiness:
    path: "/internal/isready"
    initialDelay: 3
    timeout: 1
  resources:
    limits:
      memory: "4096Mi"
    requests:
      memory: "2048Mi"
  ingresses:
    {{#each ingresses as |url|}}
      - {{url}}
    {{/each}}
  accessPolicy:
    inbound:
      rules:
        {{#each accessPolicy.inbound.rules as |rule|}}
    - application: {{rule.application}}
      namespace: {{rule.namespace}}
      cluster: {{rule.cluster}}
        {{/each}}
  azure:
    application:
      enabled: true
      tenant: {{ azure.tenant }}
      allowAllUsers: true
  webproxy: true
  env:
    {{#each env_variables }}
- name: {{@key}}
  value: {{this}}
   {{/each}}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: grafana-lgtm
        - id: elastic-apm
  vault:
    enabled: true
    paths:
      - kvPath: {{ vault.kvPath }}
        mountPath: "/secrets/ldap"
