name: Calculate DORA metrics
on:
   push:
    branches:
      - main
jobs:
  calculate-dora-metrics:
    runs-on: ubuntu-latest
    name: Calculate Lead time for changes & Deployment frequency
    steps:
      - uses: DeveloperMetrics/lead-time-for-changes@v1.2.20
        with:
          workflows: 'Build and deploy main branch'
      - uses: DeveloperMetrics/deployment-frequency@v1.5.18
        with:
          workflows: 'Build and deploy main branch'