name: Build, push, and deploy

on:
  push:
    branches:
      - sandbox

env:
  docker_image: docker.pkg.github.com/${{ github.repository }}/navansatt:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    permissions:
      contents: "read"
      checks: "write"
      id-token: "write"
      packages: "write"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.m2
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build
        shell: bash
        run: |
          mvn clean install
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${docker_image} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${docker_image}

  deploy:
    name: Deploy to NAIS
    permissions:
      contents: "read"
      id-token: "write"
    needs: build
    if: github.ref == 'refs/heads/sandbox'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v2
        name: Dev deploy
        env:
          CLUSTER: dev-fss
          RESOURCE: nais/nais-dev.yml
          VAR: image=${{ env.docker_image }}
