name: Build and deploy main branch to dev

on:
  push:
    branches:
     - sandbox

jobs:
  build:
    permissions:
      packages: write
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: "${{ steps.set-outputs.outputs.IMAGE }}"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set version
        id: version
        shell: bash
        run: |
          TIME=$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M)
          COMMIT=$(git rev-parse --short=12 HEAD)
          echo "TIME=$TIME" >> $GITHUB_OUTPUT
          echo "VERSION=$TIME-$COMMIT" >> $GITHUB_OUTPUT

      - name: NAIS login
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: nais/login@v0
        id: login
        with:
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          team: teampensjon

      - name: Docker meta
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.login.outputs.registry }}/${{ github.repository }}/${{ github.repository_owner}}
          tags: |
            type=sha,prefix=${{ steps.version.outputs.time }}-,priority=9002

      - name: Build jar with Maven
        run: mvn clean package -DskipTests

      - name: Build and push
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Set outputs
        if: ${{ github.actor != 'dependabot[bot]' }}
        shell: bash
        id: set-outputs
        run: |
          echo "IMAGE=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> $GITHUB_OUTPUT

  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    if: github.ref == 'refs/heads/sandbox'
    needs: [build]
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v5
      - uses: nais/deploy/actions/deploy@v2
        name: 'Deploy to NAIS Dev'
        env:
          IMAGE: "${{ needs.build.outputs.image }}"
          RESOURCE: nais/nais-dev.yaml
          CLUSTER: 'dev-fss'
